/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java;

import java.util.concurrent.locks.ReentrantLock;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ReentrantLock reentrantLock = new ReentrantLock();
        // 另外一个本地仓库去更新
        int count = 2;
    }
}
